[profile.default]
verbosity = 1
libs = ["lib"] # A list of library directories 
ffi = true
fs_permissions  = [{ access = "read", path = "./"}]  

[fmt]
ignore = ["test/libs/SimoConnectLib.t.sol"]

[rpc_endpoints]
polygon = "${RPC_URL}"
gnosis = "${RPC_URL}"
goerli = "${RPC_URL}"
mumbai = "${RPC_URL}"
mainnet = "${RPC_URL}"

[etherscan]
polygon = { key = "${ETHERSCAN_API_KEY}" }
gnosis = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
