[profile.default]
optimizer_runs = 1000000
verbosity = 1

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"

# [etherscan]
# goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
# mainnet = {key = "${ETHERSCAN_KEY}"}