[profile.default]
optimizer_runs = 1000000
verbosity = 1
via_ir = true

[rpc_endpoints]
goerli = "http://localhost:8545"
# mainnet = "${RPC_URL_MAINNET}"

# [etherscan]
# goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
# mainnet = {key = "${ETHERSCAN_KEY}"}
